[workspace]
resolver = "2"
members = ["modules/cli", "modules/scanner", "modules/signatures",
    "modules/arcom", "modules/common"]
default-members = ["modules/cli", "modules/scanner", "modules/arcom"]

[profile.release]
debug = true